name: Build and Deploy-2

on:
  push:
    branches:
      - main
  workflow_dispatch:

# env:
  # ACR_NAME: ${{ secrets.ACR_NAME }} # e.g., acrcapstone123
  # ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }} # e.g., acrcapstone123.azurecr.io
  # ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  # ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  # WEBAPP_NAME: ${{ secrets.WEBAPP_NAME }} # e.g., app-capstone-123
  # AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Build and Push Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: . 
      #     push: true
      #     tags: demoniiexe/actions-frontend:${{ github.sha }}

      
     

      - name: Deploy to Azure Web App-3
        uses: azure/webapps-deploy@v3
        with: 
          app-name: "yc-frontend-test"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_2 }}
          images: demoniiexe/actions-frontend:${{ github.sha }}  # Uncomment if using ACR
